/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pnls;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;

/**
 *
 * @author Sistemas-07
 */
public class PnlTableProducto extends javax.swing.JPanel {

     private PnlProducto pnlProducto ;
    
     
    /**
     * Creates new form PnlTableProducto
     */
    public PnlTableProducto() {
        initComponents();
       
    }


    

    public JLabel getLblIVA() {
        return lblIVA;
    }

    public JLabel getLblSubTotal() {
        return lblSubTotal;
    }

    public JLabel getLblTotal() {
        return lblTotal;
    }

    public JTable getTblProduc() {
        return tblProduc;
    }
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PnlTableProducto = new javax.swing.JPanel();
        scroll = new javax.swing.JScrollPane();
        tblProduc = new javax.swing.JTable();
        lblSubTotal = new javax.swing.JLabel();
        lblIVA = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        PnlTableProducto.setLayout(new java.awt.GridBagLayout());

        tblProduc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Cantidad", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scroll.setViewportView(tblProduc);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PnlTableProducto.add(scroll, gridBagConstraints);

        lblSubTotal.setText("SubTotal:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PnlTableProducto.add(lblSubTotal, gridBagConstraints);

        lblIVA.setText("IVA:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PnlTableProducto.add(lblIVA, gridBagConstraints);

        lblTotal.setText("Total:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PnlTableProducto.add(lblTotal, gridBagConstraints);

        add(PnlTableProducto, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlTableProducto;
    private javax.swing.JLabel lblIVA;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTable tblProduc;
    // End of variables declaration//GEN-END:variables
}
