/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import Pnls.PnlProducto;
import Pnls.PnlTableProducto;
import java.awt.event.ActionEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sistemas-07
 */
public class FrmFacturaDemo extends javax.swing.JFrame {
   
    private PnlProducto pnlProducto;
    private PnlTableProducto pnlTableProducto;
    private DefaultTableModel tableModel;
    
    
    /**
     * Creates new form FrmFacturaDemo
     */
    public FrmFacturaDemo() {
        
        initComponents();
        
        pnlProducto = new PnlProducto();
        pnlTableProducto = new PnlTableProducto();
        
        tableModel = new DefaultTableModel();
        tableModel = (DefaultTableModel) pnlTableProducto.getTblProduc().getModel();
        
        PnlFactura.add(pnlProducto);
        PnlTable.add(pnlTableProducto);
       
        btnAdd.addActionListener((e) -> {
            btnAddActionListener(e);
        });
       
    }
    
    
    
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlFactura = new javax.swing.JPanel();
        PnlTable = new javax.swing.JPanel();
        PnlBotton = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        PnlTableShow = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PnlFactura.setLayout(new java.awt.BorderLayout());
        getContentPane().add(PnlFactura, java.awt.BorderLayout.PAGE_START);

        PnlTable.setLayout(new java.awt.BorderLayout());

        btnAdd.setText("Add");
        PnlBotton.add(btnAdd);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        PnlBotton.add(btnDelete);

        PnlTable.add(PnlBotton, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout PnlTableShowLayout = new javax.swing.GroupLayout(PnlTableShow);
        PnlTableShow.setLayout(PnlTableShowLayout);
        PnlTableShowLayout.setHorizontalGroup(
            PnlTableShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        PnlTableShowLayout.setVerticalGroup(
            PnlTableShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 267, Short.MAX_VALUE)
        );

        PnlTable.add(PnlTableShow, java.awt.BorderLayout.CENTER);

        getContentPane().add(PnlTable, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
       
        int rowtoRemove = pnlTableProducto.getTblProduc().getSelectedRow();
        tableModel.removeRow(rowtoRemove);
        tableModel.fireTableDataChanged();
        pnlProducto.repaint();
    
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFacturaDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFacturaDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmFacturaDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFacturaDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmFacturaDemo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlBotton;
    private javax.swing.JPanel PnlFactura;
    private javax.swing.JPanel PnlTable;
    private javax.swing.JPanel PnlTableShow;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    // End of variables declaration//GEN-END:variables

    private void btnAddActionListener(ActionEvent e) {
      
        String[] row = new String[4];
      row[0] = pnlProducto.getTxtCodigo().getText();
      row[1] = pnlProducto.getTxtNombre().getText();
      row[2]= pnlProducto.getSpnCantidad().getValue().toString();
      row[3]= pnlProducto.gettxtPrecio().getText();
      
      tableModel.addRow(row);
       
      int subTotal =0;
      
        for (int i = 0; i < tableModel.getRowCount(); i++) {
          subTotal = subTotal + (Integer.parseInt((String) tableModel.getValueAt(i, 3)) * Integer.parseInt((String) tableModel.getValueAt(i, 2)));
        }
    
     pnlTableProducto.getLblSubTotal().setText("Subtotal  es:" + subTotal);
     pnlTableProducto.getLblIVA().setText("IVA:" +  (15 * subTotal) / 100);
     pnlTableProducto.getLblTotal().setText("Total:" + (subTotal + (15 * subTotal) / 100));
       
    }
}
